=== baracuda19/test/src/main/resources/momconfig.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">
	<xs:element name="momconfig">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="infrastructures" />
				<xs:element ref="serviceDefinitions" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="infrastructures">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="infrastructure" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="infrastructure">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required" />
			<xs:attribute name="host" type="xs:string" use="required" />
			<xs:attribute name="port" type="xs:nonNegativeInteger"
				use="required" />
			<xs:attribute name="channel" type="xs:string" use="required" />
			<xs:attribute name="contextFactory" type="xs:string"
				use="required" />
			<xs:attribute name="connectionFactory" type="xs:string"
				use="required" />
			<xs:attribute name="connectionType">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="JNDI" />
						<xs:enumeration value="WMQ_QUEUE" />
						<xs:enumeration value="WMQ_TOPIC" />
						<xs:enumeration value="ACTMQ_QUEUE" />
						<xs:enumeration value="ACTMQ_TOPIC" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>

			<xs:attribute name="pkgPrefixes" type="xs:string" />
			<xs:attribute name="reconnectAttempts" type="xs:nonNegativeInteger" />
			<xs:attribute name="reconnectInterval">
				<xs:simpleType>
					<xs:restriction base="xs:nonNegativeInteger">
						<xs:minInclusive value="1" />
						<xs:maxInclusive value="1000000000" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="reconnectIntervalTimeUnit">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="SECONDS" />
						<xs:enumeration value="MILLISECONDS" />
						<xs:enumeration value="MICROSECONDS" />
						<xs:enumeration value="NANOSECONDS" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="connUser" type="xs:string" />
			<xs:attribute name="connPassword" type="xs:string" />
			<xs:attribute name="brokerPubQueue" type="xs:string" />
			<xs:attribute name="brokerSubQueue" type="xs:string" />
			<xs:attribute name="failoverType">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="NONE" />
						<xs:enumeration value="PRIMARY" />
						<xs:enumeration value="SECONDARY" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="serviceDefinitions">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="serviceDefinition" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="serviceDefinition">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="destination" />
				<xs:element ref="serviceOptions" minOccurs="0" />
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required" />
			<xs:attribute name="infrastructure" type="xs:string"
				use="required" />
			<xs:attribute name="recvTimeOut">
				<xs:simpleType>
					<xs:restriction base="xs:nonNegativeInteger">
						<xs:minInclusive value="1" />
						<xs:maxInclusive value="1000000000" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="recvTimeOutTimeUnit">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="SECONDS" />
						<xs:enumeration value="MILLISECONDS" />
						<xs:enumeration value="MICROSECONDS" />
						<xs:enumeration value="NANOSECONDS" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="oneway" type="xs:boolean" />
			<xs:attribute name="multiReply" type="xs:boolean" />
			<xs:attribute name="sendTransformation" type="xs:string" />
			<xs:attribute name="receiveTransformation" type="xs:string" />
			<xs:attribute name="useAsyncMessageMap" type="xs:string" />

		</xs:complexType>
	</xs:element>
	<xs:element name="destination">
		<xs:complexType>
			<xs:attribute name="request" type="xs:string" use="required" />
			<xs:attribute name="reply" type="xs:string" />
			<xs:attribute name="nonJMSClient" type="xs:boolean" />
		</xs:complexType>
	</xs:element>
	<xs:element name="send">
		<xs:complexType>
			<xs:attribute name="minThreads">
				<xs:simpleType>
					<xs:restriction base="xs:nonNegativeInteger">
						<xs:minInclusive value="1" />
						<xs:maxInclusive value="5000" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="maxThreads">
				<xs:simpleType>
					<xs:restriction base="xs:nonNegativeInteger">
						<xs:minInclusive value="1" />
						<xs:maxInclusive value="5000" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="transacted" type="xs:boolean" />
			<xs:attribute name="timeToLive">
				<xs:simpleType>
					<xs:restriction base="xs:nonNegativeInteger">
						<xs:minInclusive value="0" />
						<xs:maxInclusive value="1000000000" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="timeToLiveTimeUnit">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="SECONDS" />
						<xs:enumeration value="MILLISECONDS" />
						<!--xs:enumeration value="MICROSECONDS"/ -->
						<!--xs:enumeration value="NANOSECONDS"/ -->
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="priority">
				<xs:simpleType>
					<xs:restriction base="xs:nonNegativeInteger">
						<xs:minInclusive value="0" />
						<xs:maxInclusive value="9" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="ackMode">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="AUTO_ACKNOWLEDGE" />
						<xs:enumeration value="CLIENT_ACKNOWLEDGE" />
						<xs:enumeration value="DUPS_OK_ACKNOWLEDGE" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="deliveryMode">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="PERSISTENT" />
						<xs:enumeration value="NON_PERSISTENT" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="msgRetryAttempts">
				<xs:simpleType>
					<xs:restriction base="xs:nonNegativeInteger">
						<xs:minInclusive value="0" />
						<xs:maxInclusive value="5000" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="msgRetryInterval">
				<xs:simpleType>
					<xs:restriction base="xs:nonNegativeInteger">
						<xs:minInclusive value="0" />
						<xs:maxInclusive value="1000000000" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="msgRetryIntervalTimeUnit">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="SECONDS" />
						<xs:enumeration value="MILLISECONDS" />
						<!--xs:enumeration value="MICROSECONDS"/ -->
						<!--xs:enumeration value="NANOSECONDS"/ -->
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="producerPooled" type="xs:boolean" />
			<xs:attribute name="useReplyTo" type="xs:boolean" />
			<xs:attribute name="producerPoolSize">
				<xs:simpleType>
					<xs:restriction base="xs:nonNegativeInteger">
						<xs:minInclusive value="1" />
						<xs:maxInclusive value="256" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="compressionThreshold">
				<xs:simpleType>
					<xs:restriction base="xs:nonNegativeInteger" />
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="compressionThresholdUnit">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="BYTES" />
						<xs:enumeration value="KILOBYTES" />
						<xs:enumeration value="MEGABYTES" />
						<xs:enumeration value="GIGABYTES" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>

			<xs:attribute name="loadBalancerType">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="ROUNDROBIN" />
						<xs:enumeration value="FAILOVER" />
						<xs:enumeration value="USE_REPLY_TO" />
						<xs:enumeration value="CONTEXT_ROUNDROBIN" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>

			<xs:attribute name="RPPCApplID">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="8" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>

			<xs:attribute name="RPPCSubSystemUser">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="4" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>

			<xs:attribute name="RPPCSubSystemDest">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="4" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>

			<xs:attribute name="RPPCClientHostName">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="4" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>

			<xs:attribute name="RPPCCarrierCode">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="3" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>

			<xs:attribute name="RPPCCityCode">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="4" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>

			<xs:attribute name="RPPCEbcdicConversion" type="xs:boolean" />

		</xs:complexType>
	</xs:element>
	<xs:element name="receive">
		<xs:complexType>
			<xs:attribute name="minThreads">
				<xs:simpleType>
					<xs:restriction base="xs:nonNegativeInteger">
						<xs:minInclusive value="1" />
						<xs:maxInclusive value="5000" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="maxThreads">
				<xs:simpleType>
					<xs:restriction base="xs:nonNegativeInteger">
						<xs:minInclusive value="1" />
						<xs:maxInclusive value="5000" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="transacted" type="xs:boolean" />
			<xs:attribute name="ASF" type="xs:boolean" />
			<xs:attribute name="selector" type="xs:string" />
			<xs:attribute name="ackMode">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="AUTO_ACKNOWLEDGE" />
						<xs:enumeration value="CLIENT_ACKNOWLEDGE" />
						<xs:enumeration value="DUPS_OK_ACKNOWLEDGE" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>

		</xs:complexType>
	</xs:element>
	<xs:element name="serviceOptions">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="send" />
				<xs:element ref="receive" />
				<xs:element name="atLeastOneInfrastructureAvailable" type="xs:boolean" minOccurs="0" maxOccurs="1" />				
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== baracuda19/test/src/test/performance/momconfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<momconfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="momconfig.xsd">
	<infrastructures>
		<!-- Development -->
		<infrastructure name="development-raf1" host="ctovm2092.dev.sabre.com"
			port="1914" channel="CHLMOM.2SG.SAAP" connectionFactory="DMOMQM01"
			contextFactory="com.ibm.mq.jms.context.WMQInitialContextFactory"
			reconnectInterval="30" reconnectIntervalTimeUnit="SECONDS"
			reconnectAttempts="100000" />
		<infrastructure name="development-raf2" host="ctovm2093.dev.sabre.com"
			port="2014" channel="CHLMOM.2SG.SAAP" connectionFactory="DMOMQM02"
			contextFactory="com.ibm.mq.jms.context.WMQInitialContextFactory"
			reconnectInterval="30" reconnectIntervalTimeUnit="SECONDS"
			reconnectAttempts="100000" />
		<infrastructure name="development-PubSub"
			host="tcp://mo.dev.sabre.com:6333,tcp://mo.dev.sabre.com:6333" port="0"
			channel="" connectionFactory="myFactory" connectionType="JNDI"
			contextFactory="com.tibco.tibjms.naming.TibjmsInitialContextFactory"
			pkgPrefixes="com.tibco.tibjms.naming" connUser="stpsuser"
			connPassword="stpsuser" reconnectInterval="30"
			reconnectIntervalTimeUnit="SECONDS" reconnectAttempts="100000" />
		<!-- Performance -->
		<infrastructure name="performance-raf1" host="plabb289.dev.sabre.com"
			port="1914" channel="CHLMOM.2SG.SAAP" connectionFactory="DMOMQM01"
			contextFactory="com.ibm.mq.jms.context.WMQInitialContextFactory"
			reconnectInterval="30" reconnectIntervalTimeUnit="SECONDS"
			reconnectAttempts="100000" />
		<infrastructure name="performance-raf2" host="plabb290.dev.sabre.com"
			port="2014" channel="CHLMOM.2SG.SAAP" connectionFactory="DMOMQM02"
			contextFactory="com.ibm.mq.jms.context.WMQInitialContextFactory"
			reconnectInterval="30" reconnectIntervalTimeUnit="SECONDS"
			reconnectAttempts="100000" />
		<infrastructure name="performance-PubSub"
			host="tcp://plabq08.dev.sabre.com:65000,tcp://plabq08.dev.sabre.com:65000"
			port="0" channel="" connectionFactory="myFactory" connectionType="JNDI"
			contextFactory="com.tibco.tibjms.naming.TibjmsInitialContextFactory"
			pkgPrefixes="com.tibco.tibjms.naming" connUser="stpsuser"
			connPassword="stpsuser" reconnectInterval="30"
			reconnectIntervalTimeUnit="SECONDS" reconnectAttempts="100000" />
		<!-- Certification -->
		<infrastructure name="certification-raf1" host="momhlc219.sabre.com"
			port="1914" channel="CHLMOM.2SG.SAAP" connectionFactory="CSAAPQM01"
			contextFactory="com.ibm.mq.jms.context.WMQInitialContextFactory"
			reconnectInterval="30" reconnectIntervalTimeUnit="SECONDS"
			reconnectAttempts="100000" />
		<infrastructure name="certification-raf2" host="momhlc219.sabre.com"
			port="2014" channel="CHLMOM.2SG.SAAP" connectionFactory="CSAAPQM02"
			contextFactory="com.ibm.mq.jms.context.WMQInitialContextFactory"
			reconnectInterval="30" reconnectIntervalTimeUnit="SECONDS"
			reconnectAttempts="100000" />
		<infrastructure name="certification-raf3" host="momhlc219.sabre.com"
			port="1915" channel="CHLMOM.2SG.SAAP" connectionFactory="CSAAPQM03"
			contextFactory="com.ibm.mq.jms.context.WMQInitialContextFactory"
			reconnectInterval="30" reconnectIntervalTimeUnit="SECONDS"
			reconnectAttempts="100000" />
		<infrastructure name="certification-raf4" host="momhlc219.sabre.com"
			port="2015" channel="CHLMOM.2SG.SAAP" connectionFactory="CSAAPQM04"
			contextFactory="com.ibm.mq.jms.context.WMQInitialContextFactory"
			reconnectInterval="30" reconnectIntervalTimeUnit="SECONDS"
			reconnectAttempts="100000" />
		<infrastructure name="certification-PubSub"
			host="tcp://jms-pubsub.cert.sabre.com:65000,tcp://jms-pubsub.cert.sabre.com:60000"
			port="0" channel="" connectionFactory="myFactory" connectionType="JNDI"
			contextFactory="com.tibco.tibjms.naming.TibjmsInitialContextFactory"
			pkgPrefixes="com.tibco.tibjms.naming" connUser="stpsuser"
			connPassword="cstpsuser" reconnectInterval="30"
			reconnectIntervalTimeUnit="SECONDS" reconnectAttempts="100000" />
		<!-- Production -->
		<infrastructure name="production-PubSub"
			host="tcp://jms-pubsub.prod.sabre.com:36000,tcp://jms-pubsub.prod.sabre.com:60000"
			port="0" channel="" connectionFactory="myFactory" connectionType="JNDI"
			contextFactory="com.tibco.tibjms.naming.TibjmsInitialContextFactory"
			pkgPrefixes="com.tibco.tibjms.naming" connUser="stpsuser"
			connPassword="pstpsuser" reconnectInterval="30"
			reconnectIntervalTimeUnit="SECONDS" reconnectAttempts="100000" />
	</infrastructures>
	<serviceDefinitions>
		<serviceDefinition name="local-RafService"
			infrastructure="development-raf1,development-raf2" recvTimeOut="20"
			recvTimeOutTimeUnit="SECONDS" sendTransformation="COMPRESS"
			receiveTransformation="COMPRESS">
			<destination request="QMOM.2SG.RQ.SAAP.ALL" reply="QMOM.SAAP.RS.2SG.ALL" />
			<serviceOptions>
				<send minThreads="10" maxThreads="20" timeToLive="20"
					timeToLiveTimeUnit="SECONDS" compressionThresholdUnit="KILOBYTES"
					compressionThreshold="128" />
				<receive minThreads="10" maxThreads="20" selector="EnvType = 'local'" />
			</serviceOptions>
		</serviceDefinition>
		<serviceDefinition name="ci-RafService"
			infrastructure="development-raf1,development-raf2" recvTimeOut="20"
			recvTimeOutTimeUnit="SECONDS" sendTransformation="COMPRESS"
			receiveTransformation="COMPRESS">
			<destination request="QMOM.2SG.RQ.SAAP.ALL" reply="QMOM.SAAP.RS.2SG.ALL" />
			<serviceOptions>
				<send minThreads="10" maxThreads="20" timeToLive="20"
					timeToLiveTimeUnit="SECONDS" compressionThresholdUnit="KILOBYTES"
					compressionThreshold="128" />
				<receive minThreads="10" maxThreads="20" selector="EnvType = 'ci'" />
			</serviceOptions>
		</serviceDefinition>
		<serviceDefinition name="development-RafService"
			infrastructure="development-raf1,development-raf2" recvTimeOut="20"
			recvTimeOutTimeUnit="SECONDS" sendTransformation="COMPRESS"
			receiveTransformation="COMPRESS">
			<destination request="QMOM.2SG.RQ.SAAP.ALL" reply="QMOM.SAAP.RS.2SG.ALL" />
			<serviceOptions>
				<send minThreads="1" maxThreads="1" timeToLive="20"
					timeToLiveTimeUnit="SECONDS" compressionThresholdUnit="KILOBYTES"
					compressionThreshold="128" />
				<receive minThreads="1" maxThreads="1" />
			</serviceOptions>
		</serviceDefinition>
		<serviceDefinition name="performance-RafService"
			infrastructure="performance-raf1,performance-raf2" recvTimeOut="20"
			recvTimeOutTimeUnit="SECONDS" sendTransformation="COMPRESS"
			receiveTransformation="COMPRESS">
			<destination request="QMOM.2SG.RQ.SAAP.ALL" reply="QMOM.SAAP.RS.2SG.ALL" />
			<serviceOptions>
				<send minThreads="100" maxThreads="200" timeToLive="20"
					timeToLiveTimeUnit="SECONDS" compressionThresholdUnit="KILOBYTES"
					compressionThreshold="128" />
				<receive minThreads="100" maxThreads="200" />
			</serviceOptions>
		</serviceDefinition>
		<serviceDefinition name="certification-RafService"
			infrastructure="certification-raf1,certification-raf2,certification-raf3,certification-raf4"
			recvTimeOut="20" recvTimeOutTimeUnit="SECONDS" sendTransformation="COMPRESS"
			receiveTransformation="COMPRESS">
			<destination request="QMOM.2SG.RQ.SAAP.ALL" reply="QMOM.SAAP.RS.2SG.ALL" />
			<serviceOptions>
				<send minThreads="10" maxThreads="150" timeToLive="20"
					timeToLiveTimeUnit="SECONDS" compressionThresholdUnit="KILOBYTES"
					compressionThreshold="128" />
				<receive minThreads="10" maxThreads="150" />
			</serviceOptions>
		</serviceDefinition>
		<serviceDefinition name="production-RafService"
			infrastructure="development-raf1,development-raf2" recvTimeOut="20"
			recvTimeOutTimeUnit="SECONDS" sendTransformation="COMPRESS"
			receiveTransformation="COMPRESS">
			<destination request="QMOM.2SG.RQ.SAAP.ALL" reply="QMOM.SAAP.RS.2SG.ALL" />
			<serviceOptions>
				<send minThreads="10" maxThreads="150" timeToLive="20"
					timeToLiveTimeUnit="SECONDS" compressionThresholdUnit="KILOBYTES"
					compressionThreshold="128" />
				<receive minThreads="10" maxThreads="150" />
			</serviceOptions>
		</serviceDefinition>
		<serviceDefinition name="local-METRICS"
			infrastructure="development-PubSub" recvTimeOut="5000"
			recvTimeOutTimeUnit="MILLISECONDS" oneway="true">
			<destination request="ICELOG.METRICS.CIO.STPS" />
			<serviceOptions>
				<send minThreads="1" maxThreads="1" timeToLive="60000"
					timeToLiveTimeUnit="MILLISECONDS" />
				<receive minThreads="1" maxThreads="1" />
			</serviceOptions>
		</serviceDefinition>
		<serviceDefinition name="ci-METRICS" infrastructure="development-PubSub"
			recvTimeOut="5000" recvTimeOutTimeUnit="MILLISECONDS" oneway="true">
			<destination request="ICELOG.METRICS.CIO.STPS" />
			<serviceOptions>
				<send minThreads="1" maxThreads="1" timeToLive="60000"
					timeToLiveTimeUnit="MILLISECONDS" />
				<receive minThreads="1" maxThreads="1" />
			</serviceOptions>
		</serviceDefinition>
		<serviceDefinition name="development-METRICS"
			infrastructure="development-PubSub" recvTimeOut="5000"
			recvTimeOutTimeUnit="MILLISECONDS" oneway="true">
			<destination request="ICELOG.METRICS.CIO.STPS" />
			<serviceOptions>
				<send minThreads="1" maxThreads="1" timeToLive="60000"
					timeToLiveTimeUnit="MILLISECONDS" />
				<receive minThreads="1" maxThreads="1" />
			</serviceOptions>
		</serviceDefinition>
		<serviceDefinition name="performance-METRICS"
			infrastructure="performance-PubSub" recvTimeOut="5000"
			recvTimeOutTimeUnit="MILLISECONDS" oneway="true">
			<destination request="ICELOG.METRICS.CIO.STPS" />
			<serviceOptions>
				<send minThreads="1" maxThreads="1" timeToLive="60000"
					timeToLiveTimeUnit="MILLISECONDS" />
				<receive minThreads="1" maxThreads="1" />
			</serviceOptions>
		</serviceDefinition>
		<serviceDefinition name="certification-METRICS"
			infrastructure="certification-PubSub" recvTimeOut="5000"
			recvTimeOutTimeUnit="MILLISECONDS" oneway="true">
			<destination request="ICELOG.METRICS.CIO.STPS" />
